package cn.lxtkj.model;
// Generated 2019-4-18 22:07:34 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Catalog generated by hbm2java
 */
public class Catalog implements java.io.Serializable {

	private Integer catalogid;
	private String catalogname;
	private Set flowers = new HashSet(0);

	public Catalog() {
	}

	public Catalog(String catalogname, Set flowers) {
		this.catalogname = catalogname;
		this.flowers = flowers;
	}

	public Integer getCatalogid() {
		return this.catalogid;
	}

	public void setCatalogid(Integer catalogid) {
		this.catalogid = catalogid;
	}

	public String getCatalogname() {
		return this.catalogname;
	}

	public void setCatalogname(String catalogname) {
		this.catalogname = catalogname;
	}

	public Set getFlowers() {
		return this.flowers;
	}

	public void setFlowers(Set flowers) {
		this.flowers = flowers;
	}

}
