package cn.lxtkj.model;
// Generated 2019-4-18 22:07:34 by Hibernate Tools 4.0.0

/**
 * Orderitem generated by hbm2java
 */
public class Orderitem implements java.io.Serializable {

	private Integer orderitemid;
	private Flower flower;
	private Orders orders;
	private Integer quantity;

	public Orderitem() {
	}

	public Orderitem(Flower flower, Orders orders, Integer quantity) {
		this.flower = flower;
		this.orders = orders;
		this.quantity = quantity;
	}

	public Integer getOrderitemid() {
		return this.orderitemid;
	}

	public void setOrderitemid(Integer orderitemid) {
		this.orderitemid = orderitemid;
	}

	public Flower getFlower() {
		return this.flower;
	}

	public void setFlower(Flower flower) {
		this.flower = flower;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
