package cn.lxtkj.model;
// Generated 2019-4-18 22:07:34 by Hibernate Tools 4.0.0

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer pid;
	private String pname;
	private Double price;

	public Product() {
	}

	public Product(String pname, Double price) {
		this.pname = pname;
		this.price = price;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

}
