package cn.lxtkj.model;
// Generated 2019-4-18 22:07:34 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userid;
	private String username;
	private String password;
	private String role;
	private Set orderses = new HashSet(0);
	private Userdetail userdetail;
//	private Set guashis = new HashSet(0);
	private Guashi guashi;

	public User() {
	}

	public User(String username, String password, String role, Set orderses, Userdetail userdetail, Guashi guashi) {
		this.username = username;
		this.password = password;
		this.role = role;
		this.orderses = orderses;
		this.userdetail = userdetail;
		this.guashi = guashi;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

	public Userdetail getUserdetail() {
		return this.userdetail;
	}

	public void setUserdetail(Userdetail userdetail) {
		this.userdetail = userdetail;
	}

	public Guashi getGuashi() {
		return guashi;
	}

	public void setGuashi(Guashi guashi) {
		this.guashi = guashi;
	}

	

}
