package cn.lxtkj.model;
// Generated 2019-4-18 22:07:34 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Userdetail generated by hbm2java
 */
public class Userdetail implements java.io.Serializable {

	private Integer userid;
	private User user;
	private Byte xb;
	private String truename;
	private Date csrq;
	private String phone;
	private String email;
	private String address;

	public Userdetail() {
	}

	public Userdetail(User user) {
		this.user = user;
	}

	public Userdetail(User user, Byte xb, String truename, Date csrq, String phone, String email, String address) {
		this.user = user;
		this.xb = xb;
		this.truename = truename;
		this.csrq = csrq;
		this.phone = phone;
		this.email = email;
		this.address = address;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}


	public Byte getXb() {
		return xb;
	}

	public void setXb(Byte xb) {
		this.xb = xb;
	}

	public String getTruename() {
		return this.truename;
	}

	public void setTruename(String truename) {
		this.truename = truename;
	}

	public Date getCsrq() {
		return this.csrq;
	}

	public void setCsrq(Date csrq) {
		this.csrq = csrq;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
